### ISSUE TITLE
about data preprocessing

### ISSUE THREAD

**Issue by YanbingXu** [QianSong-Cherry/SAR-ZSL_for_featureSpace#1]
hi there,is there any chance i can know about how u process your SAR data.because when i use your code on my own data,its hard for me to get the same results.my loss is huge and i can hardly generate any meaningful images. the way i process the data is clip to 128, use the log-Amplitude image of raw images. label has changed to one-hot.

**Comment by QianSong-Cherry** [comment]
> hi there,is there any chance i can know about how u process your SAR data.because when i use your code on my own data,its hard for me to get the same results.my loss is huge and i can hardly generate any meaningful images. the way i process the data is clip to 128, use the log-Amplitude image of raw images. label has changed to one-hot.

Sorry for letting you waiting for so long. My suggestion is that you should scale the data to [0, 1].
